#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server

PATH_TO_FILE=$1
IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4

if [ $# -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ $# -lt 4 ]; then
    # Attempt to transfer with default ssh key
    scp -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USERNAME@$IP:~/"
else
    # Transfer with specified key
    scp -i "$PATH_TO_SSH_KEY" -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USERNAME@$IP:~/"
fi
