#!/usr/bin/env bash
# This script installs and configures the Nginx web server

# Update package lists
apt-get update

# Install Nginx
apt-get -y install nginx

# Allow HTTP traffic through firewall (UFW)
ufw allow 'Nginx HTTP'

# Create a simple HTML page
echo "Hello World!" > /var/www/html/index.html

# Start the Nginx service
service nginx start
