#!/usr/bin/env bash
# Script to configure Nginx server to redirect /redirect_me

# Update package index and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Define the new site URL and the string for replacement
new_site="www.youtube.com/@naturethrillers/videos"
replacement="location /redirect_me {\n\treturn 301 https:\/\/$new_site;\n}"

# Use sed to replace the appropriate line in the Nginx configuration file
sudo sed -i "/^\s*server\s*{[^}]*$/a $replacement" /etc/nginx/sites-available/default

# Restart Nginx to apply the configuration changes
sudo service nginx restart
