#!/usr/bin/env bash
# This script installs and configures HAProxy
# to distribute traffic to two web servers - web-01 and web-02
# using roundrobin algorithm

sudo apt-get -y update
apt-get -y install haproxy

# edit config file
HAProxy_config=\
"
frontend  iygeal_backend
        bind *:80
        mode http
        default_backend iygeal_backend
backend iygeal_backend
        balance roundrobin
        server 63210-web-01 100.26.216.116:80 check
        server 63210-web-02 3.84.161.102:80 check
"
echo "$HAProxy_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
