#!/usr/bin/env bash
# Bash script that generates a MySQL dump
# and creates a compressed archive out of it.

# Set the password for MySQL root user
MYSQL_PASSWORD="$1"

# Get the current date in the specified format (day-month-year)
DATE=$(date +"%d-%m-%Y")

# Define the MySQL dump filename
MYSQL_DUMP_FILE="backup.sql"

# Define the tar.gz archive filename
ARCHIVE_FILE="$DATE.tar.gz"

# Generate MySQL dump
mysqldump -u root -p"$MYSQL_PASSWORD" --all-databases > "$MYSQL_DUMP_FILE"

# Compress the MySQL dump into a tar.gz archive
tar -czvf "$ARCHIVE_FILE" "$MYSQL_DUMP_FILE"
