#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely with a sleep 2 in between each iteration.
# It also responds to SIGTERM signal with "I am invincible!!!"

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM
done
