#!/usr/bin/env bash
#  manage_my_process Bash script

PID_FILE="/var/run/my_process.pid"
LOG_FILE="/tmp/my_process"

# Function to start manage_my_process
start_process() {
	nohup ./manage_my_process >> "$LOG_FILE" 2>&1 &
	echo "$!" > "$PID_FILE"
	echo "manage_my_process started"
}

#  Function to stop manage_my_process
stop_process() {
	if [ -f '$PID_FILE' ]; then
		pid=$(cat "PID_FILE")
		kill "$pid"
		rm -f "PID_FILE"
		echo "manage_my_process stopped"
	fi
}
#  Function to restart manage_my_process
restart_process() {
	stop_process
	start_process
	echo "manage_my_process restarted"
}
#  Check for the argument and call the appropriate function
case "$1" in
	start)
		start_process
		;;
	stop)
		stop_process
		;;
	restart)
		restart_process
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		;;
esac