#!/usr/bin/env bash

# Bash script to tell a story based on the contents of the `/etc/passwd` file using a while loop and IFS.

  # Read the file line by line using a while loop and IFS
  while IFS=':' read -r username password uid gid info home shell; do
    # Display the formatted information
    echo "The user $username is part of the $gid gang," \
         "lives in $home and rides $shell." \
         "$uid's place is protected by the passcode $password," \
         "more info about the user here: $info"
  done < "/etc/passwd"
