#!/usr/bin/env bash
# Bash script to display visitor IP and HTTP status code from the Apache log file using awk

# Check if the file exists
if [ -e "$apache-access.log" ]; then

  # Use awk to extract and format IP and HTTP status code
  awk '{print $1 " " $9}' "$apache-access.log"

else
  echo "Error: $apache-access.log does not exist."
fi
