#!/usr/bin/env bash
#  Bash script that prints string using while loop and if statement

counter=1
while [ $counter -le 10 ]; do
if [ $counter -eq 9 ]; then
	echo "Best School"
	echo "Hi"
else
	echo "Best School"
fi
((counter++))
done
