#!/usr/bin/env bash
#  Bash script that prints different messages, origins of some messages
counter=1
while [ $counter -le 20 ]; do
#  Use case statement to check for specific loop iterations
case $counter in
4)
	echo $counter
	echo "bad luck from China"
	;;
9)
	echo $counter
	echo "bad luck from Japan"
	;;
17)
	echo $counter
	echo "bad luck from Italy"
	;;
*)
	echo $counter
esac
((counter++))
done