#!/usr/bin/env bash
#  Bash script that configures an Ubuntu server as follows:
#+ localhost resolves to 127.0.0.2 and
#+ facebook.com resolves to 8.8.8.8

# Make a copy of the hosts file in home directory
cp /etc/hosts ~/hosts.old

#  Configure the file as desired
echo "127.0.0.2		localhost" > ~/hosts.old
echo "8.8.8.8		facebook.com" >> ~/hosts.old

# Overwrite the original /etc/hosts with the modified file
cp -f ~/hosts.old /etc/hosts
