#!/usr/bin/env bash
# This script gracefully reloads the Gunicorn service

# Send the HUP signal to gracefully reload Gunicorn
# Gunicorn interprets this signal as an instruction to reload.
pkill --signal HUP gunicorn
